In [37]:
import nltk
import pickle

filename = 'model.pkl'
loaded_model = pickle.load(open(filename, 'rb'))
result = loaded_model.score(X_test, Y_test)

NameError: name 'X_test' is not defined

In [25]:
import pandas as pd
df = pd.read_csv("fraud_detection.csv")

In [26]:
df.head(-40)

,Unnamed: 0,kdkc,typeppk,jkpst,umur,jnspelsep,los,cmg,severitylevel,diagprimer,...,proc58_62,proc63_67,proc68_70,proc71_73,proc74_75,proc76_77,proc78_79,proc80_99,proce00_e99,label
0,0,1107,SB,1,lima,2,outpatient,F,0,f00_f99,...,0,0,0,0,0,0,0,0,0,1
1,1,1303,C,0,empat,1,medium stay,E,3,e00_e90,...,0,0,0,0,0,0,0,4,0,1
2,2,1114,B,1,empat,2,outpatient,Q,0,r00_r99,...,0,0,0,0,0,0,0,0,0,1
3,3,601,SC,0,empat,2,outpatient,Q,0,r00_r99,...,0,0,0,0,0,0,0,0,0,1
4,4,1006,B,0,empat,2,outpatient,F,0,f00_f99,...,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200172,200172,1001,SC,1,lima,2,outpatient,Q,0,h00_h59,...,0,0,0,0,0,0,0,1,0,0
200173,200173,1107,B,1,empat,2,outpatient,Q,0,k00_k93,...,0,0,0,0,0,0,0,1,0,0
200174,200174,604,B,1,empat,2,outpatient,Q,0,e00_e90,...,0,0,0,0,0,0,0,1,0,0
200175,200175,904,KC,1,empat,1,short stay,I,2,q00_q99,...,0,0,0,0,0,0,0,1,0,0
200176,200176,1601,SC,0,satu,2,outpatient,F,0,f00_f99,...,0,0,0,0,0,0,0,0,0,0

In [27]:

df.drop(['diagprimer', 'dx2_a00_b99', 'dx2_c00_d48',
       'dx2_d50_d89', 'dx2_e00_e90', 'dx2_f00_f99', 'dx2_g00_g99',
       'dx2_h00_h59', 'dx2_h60_h95', 'dx2_i00_i99', 'dx2_j00_j99',
       'dx2_l00_l99', 'dx2_m00_m99', 'dx2_n00_n99', 'dx2_o00_o99',
       'dx2_p00_p96', 'dx2_q00_q99', 'dx2_r00_r99', 'dx2_s00_t98',
       'dx2_v01_y98', 'dx2_z00_z99', 'proc00_13', 'proc14_23', 'proc24_27',
       'proc28_28', 'proc29_31', 'proc_32_38', 'proc39_45', 'proc46_51',
       'proc52_57', 'proc58_62', 'proc63_67', 'proc68_70', 'proc71_73',
       'proc74_75', 'proc76_77', 'proc78_79', 'proc80_99', 'proce00_e99' ], axis=1, inplace=True)

In [28]:
df.columns

Index(['Unnamed: 0', 'kdkc', 'typeppk', 'jkpst', 'umur', 'jnspelsep', 'los',
       'cmg', 'severitylevel', 'label'],
      dtype='object')

In [29]:
df

,Unnamed: 0,kdkc,typeppk,jkpst,umur,jnspelsep,los,cmg,severitylevel,label
0,0,1107,SB,1,lima,2,outpatient,F,0,1
1,1,1303,C,0,empat,1,medium stay,E,3,1
2,2,1114,B,1,empat,2,outpatient,Q,0,1
3,3,601,SC,0,empat,2,outpatient,Q,0,1
4,4,1006,B,0,empat,2,outpatient,F,0,1
...,...,...,...,...,...,...,...,...,...,...
200212,200212,2102,B,1,empat,2,outpatient,Z,0,0
200213,200213,1308,SD,0,satu,2,outpatient,Q,0,0
200214,200214,201,SB,1,dua,2,outpatient,Q,0,0
200215,200215,1008,B,1,empat,1,outpatient,J,1,0
200216,200216,1016,SC,0,dua,1,outpatient,K,1,0

In [30]:
C = (df.dtypes == 'object')
C2 = (df.dtypes == 'category')
CategoricalVariables = list(C[C].index) + list(C2[C2].index)

Integer = (df.dtypes == 'int64')
Float = (df.dtypes == 'float64')
NumericVariables = list(Integer[Integer].index) + list(Float[Float].index)

df_kategori = pd.get_dummies(df[CategoricalVariables], columns=CategoricalVariables)
df_numeric = df[NumericVariables]

df_dummy = pd.get_dummies(df[CategoricalVariables], columns=CategoricalVariables)
df_numeric = df[NumericVariables]

df_numeric["id"] = df_numeric.index + 1
df_dummy["id"] = df_dummy.index + 1
bpjs_data_final = pd.merge(df_dummy, df_numeric ,on="id")
response = ['Response']
VariablesNoTarget = [x for x in bpjs_data_final.columns if x not in response]
bpjs_data_final.drop(['id'], axis=1, inplace=True)
print("Dummy transformation was successful")

Dummy transformation was successful

C:\Users\tampu\AppData\Local\Temp\ipykernel_17012\2101372619.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_numeric["id"] = df_numeric.index + 1

In [32]:
bpjs_data_final.drop(['label'], axis=1, inplace=True)

KeyError: "['label'] not found in axis"

In [34]:
x = loaded_model.predict(bpjs_data_final.iloc[200172].values.reshape(1,-1))

TypeError: MLPClassifier.predict() missing 1 required positional argument: 'X'

In [18]:

bpjs_data_final

,typeppk_A,typeppk_B,typeppk_C,typeppk_D,typeppk_GD,typeppk_HD,typeppk_I1,typeppk_I2,typeppk_I3,typeppk_I4,...,cmg_T,cmg_U,cmg_V,cmg_W,cmg_Z,Unnamed: 0,kdkc,jkpst,jnspelsep,severitylevel
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1107,1,2,0
1,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,1,1303,0,1,3
2,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,2,1114,1,2,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,3,601,0,2,0
4,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,4,1006,0,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200212,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,1,200212,2102,1,2,0
200213,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,200213,1308,0,2,0
200214,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,200214,201,1,2,0
200215,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,200215,1008,1,1,1
200216,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,200216,1016,0,1,1

In [21]:
out = round(x[0], 2)
out

NameError: name 'x' is not defined

In [22]:

if (out == 0):
  print("fraud")
else:
  print( "not fraud")

NameError: name 'out' is not defined